[package]
description = "CosmWasm integration testing for Aura"
edition = "2021"
license = "MIT OR Apache-2.0"
name = "aura-test-tube"
repository = "github.com/aura-nw/test-tube/aura-test-tube"
version = "1.1.1"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

exclude = [
  "aura",
  "test_artifacts",
]

[dependencies]
base64 = "0.13.0"
cosmrs = {version = "0.12.0", features = ["cosmwasm"]}
cosmos-sdk-proto = { version = "0.20.0", default-features = false, features = ["cosmwasm"] }
aura-proto = {version = "1.1.1", path = "../aura-proto"}
cosmwasm-schema = "1.1.2"
cosmwasm-std = "1.1.2"
prost = "0.12.0"
prost-types = "0.12.1"
serde = "1.0.144"
serde_json = "1.0.85"
test-tube = {version = "0.1.1", path = "../test-tube"}
thiserror = "1.0.34"

[build-dependencies]
bindgen = "0.68.1"

[dev-dependencies]
rayon = "1.5.3"
