[package]
description = "CosmWasm integration testing for Aura"
edition = "2021"
license = "MIT OR Apache-2.0"
name = "aura-test-tube"
repository = "github.com/aura-nw/test-tube/aura-test-tube"
version = "0.1.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

exclude = [
  "aura",
  "test_artifacts",
]

[dependencies]
base64 = "0.21.4"
cosmrs = {version = "0.14.0", features = ["cosmwasm"]}
aura-std = {version = "0.1.0", path = "../../lib/aura-std"}
cosmwasm-schema = "1.1.2"
cosmwasm-std = "1.1.2"
prost = "0.12.0"
prost-types = "0.12.1"
serde = "1.0.144"
serde_json = "1.0.85"
test-tube = {version = "0.1.0", path = "../test-tube"}
thiserror = "1.0.34"

[build-dependencies]
bindgen = "0.68.1"

[dev-dependencies]
rayon = "1.5.3"
