[package]
description = "library for building integration testing environments for cosmos-sdk chains in Rust"
edition = "2021"
license = "MIT OR Apache-2.0"
name = "test-tube"
repository = "https://github.com/osmosis-labs/test-tube"
version = "0.1.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
cosmrs = {version = "0.12.0", features = ["cosmwasm"]}
cosmos-sdk-proto = "0.19.0"
cosmwasm-std = "1.1.2"
osmosis-std = {version = "0.13.2"}
prost = "0.11.0"
serde = "1.0.144"
serde_json = "1.0.85"
thiserror = "1.0.34"

[dev-dependencies]
cw1-whitelist = "0.15.0"
rayon = "1.5.3"
